"""empty message

Revision ID: 02457daf399b
Revises: 5aa21d6539bd
Create Date: 2020-02-23 11:52:37.017374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02457daf399b'
down_revision = '5aa21d6539bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
