"""empty message

Revision ID: 43db77b96ab2
Revises: 600c5df3b23c
Create Date: 2020-02-23 20:31:50.841190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43db77b96ab2'
down_revision = '600c5df3b23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', '_status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('_role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_role')
    op.alter_column('orders', '_status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
